{% set name = "pz-rail-sklearn" %}
{% set version = "2.0.2" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pz_rail_sklearn-{{ version }}.tar.gz
  sha256: 8b26615a8834a5f1488be7cebe08bf7c410e1b011b8dbe35fda01fc1dff67df6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - pz-rail-base >=1.0.3
    - scikit-learn
    - pandas
test:
  imports:
    - rail.sklearn
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  license: MIT
  license_file: LICENSE
  home: https://github.com/LSSTDESC/rail_sklearn
  summary: RAIL estimators using scikit-learn regressors
  description: |
    RAIL is a flexible software library providing tools to produce at-scale photometric redshift data products, including uncertainties and summary statistics, and stress-test them under realistically complex systematics. 

extra:
  recipe-maintainers:
    - sschmidt23
    - eacharles
